hyperfleet-adapter:
  image:
    registry: quay.io/openshift-hyperfleet
    repository: hyperfleet-adapter
    pullPolicy: Always
    tag: v0.1.1

  adapterConfig:
    create: true
    # injected via ArgoCD fileParameters or --set-file at install time

  adapterTaskConfig:
    create: false
    configMapName: placement-adapter-resources

  broker:
    create: true
    googlepubsub:
      projectId: "dev-reg-us-c1-ckandagb3fc"
      subscriptionId: hyperfleet-cluster-events-adapter-placement-job
      topic: hyperfleet-cluster-events
      createTopicIfMissing: false
      createSubscriptionIfMissing: false

  serviceAccount:
    create: true
    name: hyperfleet-adapter-placement-job
    annotations:
      iam.gke.io/gcp-service-account: placement-adapter@dev-reg-us-c1-ckandagb3fc.iam.gserviceaccount.com

  env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          fieldPath: spec.serviceAccountName
    - name: GCP_PROJECT_ID
      value: "dev-reg-us-c1-ckandagb3fc"
    - name: MAESTRO_URL
      value: "http://maestro.hyperfleet.svc.cluster.local:8000"
    - name: HYPERFLEET_API_URL
      value: "http://hyperfleet-api.hyperfleet.svc.cluster.local:8000"
    - name: PLACEMENT_IMAGE
      value: "google/cloud-sdk:slim"

  rbac:
    resources:
      - configmaps
      - jobs
      - jobs/status
      - pods
