{{- if .Values.gcpResources.enabled }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ .Values.gcpResources.serviceAccount.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.gcpResources.projectId | quote }}
    argocd.argoproj.io/sync-wave: "-2"
spec:
  displayName: {{ .Values.gcpResources.serviceAccount.displayName | quote }}
  description: {{ .Values.gcpResources.serviceAccount.description | quote }}
{{- end }}
