apiVersion: v1
kind: ConfigMap
metadata:
  name: signing-key-adapter-resources
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: signing-key-adapter
    app.kubernetes.io/component: adapter-task-config
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  task-config.yaml: |
    {{- .Files.Get "adapter-task-config.yaml" | nindent 4 }}
  manifestwork.yaml: |
    {{- .Files.Get "adapter-task-resource-manifestwork.yaml" | nindent 4 }}
